services:
  frontend-builder:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./webserver/frontend/frontend:/output
    command: sh -c "npm install && npm run build -- --output-path=dist && cp -r dist/* /output"

  backend-server:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node api.js"
    restart: unless-stopped

  frontend-server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./webserver/frontend:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && node server.js"
    depends_on:
      - frontend-builder
